[package]
name = "visual_mem_alloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston2d-graphics = "0.44.0"
piston_window = "0.131.0"
rand = "0.8.5"
