[package]
name = "uniqr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.86"
assert_cmd = "2.0.15"
predicates = "3.1.2"
pretty_assertions = "1.4.0"
rand = "0.8.5"
tempfile = "3.10.1"
